### ISSUE TITLE
llama3 finetune time

### ISSUE THREAD

**Issue by Xiaohui9607** [xiaoachen98/Open-LLaVA-NeXT#11]
Hi, I am finetuning llama3-8b on the dataset you provide, with 4x8 A100s, I wonder how long does it take on your side to finish the experiment? When finetuning vicuna-7b it only took me 12 hours, but llama3-8b took me 42 hours. Is this the same case on your end? thanks

**Comment by xiaoachen98** [comment]
> Hi, I am finetuning llama3-8b on the dataset you provide, with 4x8 A100s, I wonder how long does it take on your side to finish the experiment? When finetuning vicuna-7b it only took me 12 hours, but llama3-8b took me 42 hours. Is this the same case on your end? thanks

For LLaMA3, I set the max_length to 6144. You can set this arg to 4096 back to reduce the training time.

**Comment by drizzle0171** [comment]
Hi, there!
I wonder about the training time of fine-tuning llama3-8b.

I'm fine-tuning llama3-8b on the given dataset like @Xiaohui9607.
But in my case, I'm training with 4 A100s and using the code provided by the official LLaVA-Next.

According to the expected time, the training will take 286 hours.
However, I think it's reasonable that the time will be times because I only use 4 GPUs.
Moreover, the pre-training time was similar ... (5 hours with 16 A100s VA 21 hours with 4 A100s)

Am I right ...?
