### ISSUE TITLE
does it support llava-next-video yet?

### ISSUE THREAD

**Issue by dragen1860** [xiaoachen98/Open-LLaVA-NeXT#3]
Hi, dear author: 
   since the official author did not release the llava-next training code yet, it would be very helpful for your kindly share the training part of llava-next.  I wonder does current version support llava-next-video yet?

**Comment by xiaoachen98** [comment]
> Hi, dear author: since the official author did not release the llava-next training code yet, it would be very helpful for your kindly share the training part of llava-next. I wonder does current version support llava-next-video yet?

Thanks for your appreciation. Unfortunately, since we've been catching up on the DDL for the [ShareGPT4Video](https://sharegpt4video.github.io/) project lately, the training part of llava-next-video is not currently supported. We will try to reproduce the training part of llava-next-video after the DDL.
